name: Package

on:
  push:
    branches: ["main"]
    tags:
      - v*
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Create Zip File
        uses: montudor/action-zip@v1
        if: github.head_ref == null
        with:
          args: zip -qq -r plaster-plugin.rbz src

      - name: Update latest tag
        uses: EndBug/latest-tag@v1.6.2
        if: github.ref == 'refs/heads/main'

      - name: Develop Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main'
        with:
          prerelease: true
          tag_name: latest
          files: plaster-plugin.rbz
          fail_on_unmatched_files: true
          generate_release_notes: false

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: plaster-plugin.rbz
          fail_on_unmatched_files: true
          generate_release_notes: true
          make_latest: true
